# @plugin LongerDays
# @version 1.0.10
# @author foncused

# Day cycle in minutes
day: 30

# Night cycle in minutes
night: 5

# Skip nights by meeting GameRule.PLAYERS_SLEEPING_PERCENTAGE
night-skipping: true

# Worlds to enable
worlds:
  - "world"
